### ISSUE TITLE
Problem with ESP32

### ISSUE THREAD

**Issue by ouaibeer** [Atlas-Scientific/Ezo_uart_lib#2]
This library gives error from ESP32 version 2.0.4 and newer.

`C:\Users\Eric\Documents\Arduino\libraries\Ezo_uart_lib-master\Ezo_uart.cpp:36:41: error: no matching function for call to 'Ezo_uart::send_cmd_with_num(const char [4], float&, int)'
  send_cmd_with_num("rt,", temperature, 3);
`
Is it possible to fix this?
Thank you,

**Comment by Atlas-Scientific** [comment]
Is this issue occurring with code from the example folder or with your own code? I would like the full context in which this issue is occurring to troubleshoot it.

**Comment by ouaibeer** [comment]
Hi, for example I try to compile the ezo uart example code named Serial_port_expander_tempcomp_example.ino.
I receive the following error message when compilling with esp32 2.0.7 but it's working with esp32 2.0.2.

`c:\Users\Eric\Documents\Arduino\libraries\Ezo_uart_lib-master\Ezo_uart.cpp: In member function 'uint8_t Ezo_uart::send_cmd_with_num(const char*, char*, uint8_t, float, uint8_t)':
c:\Users\Eric\Documents\Arduino\libraries\Ezo_uart_lib-master\Ezo_uart.cpp:68:56: error: call of overloaded 'String(float&, uint8_t&)' is ambiguous
  String temp = String(cmd )+ String(num, decimal_amount);
                                                        ^
In file included from C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/Arduino.h:176,
                 from c:\Users\Eric\Documents\Arduino\libraries\Ezo_uart_lib-master\Ezo_uart.cpp:2:
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:79:18: note: candidate: 'String::String(long long unsigned int, unsigned char)'
         explicit String(unsigned long long, unsigned char base = 10);
                  ^~~~~~
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:78:18: note: candidate: 'String::String(long long int, unsigned char)'
         explicit String(long long, unsigned char base = 10);
                  ^~~~~~
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:77:18: note: candidate: 'String::String(double, unsigned int)'
         explicit String(double, unsigned int decimalPlaces = 2);
                  ^~~~~~
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:76:18: note: candidate: 'String::String(float, unsigned int)'
         explicit String(float, unsigned int decimalPlaces = 2);
                  ^~~~~~
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:75:18: note: candidate: 'String::String(long unsigned int, unsigned char)'
         explicit String(unsigned long, unsigned char base = 10);
                  ^~~~~~
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:74:18: note: candidate: 'String::String(long int, unsigned char)'
         explicit String(long, unsigned char base = 10);
                  ^~~~~~
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:73:18: note: candidate: 'String::String(unsigned int, unsigned char)'
         explicit String(unsigned int, unsigned char base = 10);
                  ^~~~~~
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:72:18: note: candidate: 'String::String(int, unsigned char)'
         explicit String(int, unsigned char base = 10);
                  ^~~~~~
C:\Users\Eric\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.7\cores\esp32/WString.h:71:18: note: candidate: 'String::String(unsigned char, unsigned char)'
         explicit String(unsigned char, unsigned char base = 10);
                  ^~~~~~

exit status 1

Compilation error: exit status 1`

**Comment by Atlas-Scientific** [comment]
Ok I did a fix, try it with the latest version.

**Comment by ouaibeer** [comment]
That's working great, thank you very much. I close the issue.
